---
features:
  - Adds ``mode`` and ``properties`` fields in the portgroup object. Both of
    them are optional and can be set from the API. They are available starting
    with API microversion 1.26. If the ``mode`` field of a portgroup is not
    specified in a POST request, its value will be set to the value of the
    configuration option ``[DEFAULT]default_portgroup_mode``. The configuration
    option ``[DEFAULT]default_portgroup_mode`` has a value of ``active-backup``
    by default.
fixes:
  - |
    ``address`` field of a portgroup is optional for all API microversions.
