---
features:
  - |
    Adds new ``bios`` interface to ``irmc`` hardware type. And provide
    out-of-band BIOS configuration solution for iRMC driver which makes
    the functionality available via manual cleaning.