- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs
      - install-guide-jobs
    check:
      jobs:
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-multitenant-network
        # Non-voting jobs
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            voting: false
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-tempest-dsvm-ironic-inspector:
            voting: false
        - ironic-tempest-dsvm-pxe_ipmitool-postgres:
            voting: false
        - openstack-tox-cover
    gate:
      queue: ironic
      jobs:
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-multitenant-network


        - openstack-tox-cover
    post:
      jobs:
        - openstack-tox-cover
