- project:
    name: openstack/ironic
    check:
      jobs:
        - ironic-tempest-dsvm-pxe_ipmitool-postgres:
            voting: false
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-tempest-dsvm-ipa-partition-pxe_ipmitool-tinyipa-python3:
            voting: false
        - ironic-tempest-dsvm-ironic-inspector:
            voting: false
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-bfv
        - ironic-dsvm-standalone
        - ironic-grenade-dsvm
        - ironic-grenade-dsvm-multinode-multitenant
    gate:
      queue: ironic
      jobs:
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-bfv
        - ironic-dsvm-standalone
        - ironic-grenade-dsvm
        - ironic-grenade-dsvm-multinode-multitenant
    experimental:
      jobs:
        - ironic-dsvm-functional
        - ironic-tempest-dsvm-pxe_ipa-full:
            voting: false
        - ironic-tempest-dsvm-ipa-resourceclasses-partition-pxe_ipmitool-tinyipa:
            voting: false
