- project:
    check:
      jobs:
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-multitenant-network
        # Non-voting jobs
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            voting: false
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-tempest-dsvm-ironic-inspector:
            voting: false
        - ironic-tempest-dsvm-pxe_ipmitool-postgres:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-tempest-dsvm-ipa-partition-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-multitenant-network


